# frozen_string_literal: true

# THIS FILE WAS GENERATED BY `rake regenerate_unamespaced_shims`

# @summary DEPRECATED.  Use the namespaced function [`stdlib::to_json`](#stdlibto_json) instead.
Puppet::Functions.create_function(:to_json) do
  dispatch :deprecation_gen do
    repeated_param 'Any', :args
  end
  def deprecation_gen(*args)
    call_function('deprecation', 'to_json', 'This function is deprecated, please use stdlib::to_json instead.', false)
    call_function('stdlib::to_json', *args)
  end
end
