# frozen_string_literal: true

# THIS FILE WAS GENERATED BY `rake regenerate_unamespaced_shims`

# @summary DEPRECATED.  Use the namespaced function [`stdlib::to_python`](#stdlibto_python) instead.
Puppet::Functions.create_function(:to_python) do
  dispatch :deprecation_gen do
    repeated_param 'Any', :args
  end
  def deprecation_gen(*args)
    call_function('deprecation', 'to_python', 'This function is deprecated, please use stdlib::to_python instead.', false)
    call_function('stdlib::to_python', *args)
  end
end
