language: ruby
rvm:
  - 1.8.7
before_script:
after_script:
script: "rake spec_full"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
gemfile: .gemfile
