name    'kwilczynski/puppet-functions'
version '0.0.1'
source 'https://github.com/kwilczynski/puppet-functions'
author 'Krzysztof Wilczynski'
license 'UNKNOWN'
summary 'A set of basic functions for puppet.'
description 'This module provides a set of basic functions for puppet that extend the standard library.'
project_page 'https://github.com/kwilczynski/puppet-functions'
