name    'puppetlabs-functions'
version '0.0.1'
source 'https://github.com/puppetlabs/puppetlabs-functions'
author 'Krzysztof Wilczynski'
license 'Apache License 2.0'
summary 'A set of basic functions for puppet.'
description 'This module provides a set of basic functions for puppet that extend the standard library.'
project_page 'https://github.com/puppetlabs/puppetlabs-functions'
