# keys are real keys copied from the internet
module X509_data
  RSA_PUBLIC = <<~DOC
  -----BEGIN RSA PUBLIC KEY-----
  MIIBCgKCAQEA+xGZ/wcz9ugFpP07Nspo6U17l0YhFiFpxxU4pTk3Lifz9R3zsIsu
  ERwta7+fWIfxOo208ett/jhskiVodSEt3QBGh4XBipyWopKwZ93HHaDVZAALi/2A
  +xTBtWdEo7XGUujKDvC2/aZKukfjpOiUI8AhLAfjmlcD/UZ1QPh0mHsglRNCmpCw
  mwSXA9VNmhz+PiB+Dml4WWnKW/VHo2ujTXxq7+efMU4H2fny3Se3KYOsFPFGZ1TN
  QSYlFuShWrHPtiLmUdPoP6CV2mML1tk+l7DIIqXrQhLUKDACeM5roMx0kLhUWB8P
  +0uj1CNlNN4JRZlC7xFfqiMbFRU9Z4N6YwIDAQAB
  -----END RSA PUBLIC KEY-----
  DOC

  RSA_PRIVATE = <<-DOC
  -----BEGIN RSA PRIVATE KEY-----
  MIIBOgIBAAJBAKj34GkxFhD90vcNLYLInFEX6Ppy1tPf9Cnzj4p4WGeKLs1Pt8Qu
  KUpRKfFLfRYC9AIKjbJTWit+CqvjWYzvQwECAwEAAQJAIJLixBy2qpFoS4DSmoEm
  o3qGy0t6z09AIJtH+5OeRV1be+N4cDYJKffGzDa88vQENZiRm0GRq6a+HPGQMd2k
  TQIhAKMSvzIBnni7ot/OSie2TmJLY4SwTQAevXysE2RbFDYdAiEBCUEaRQnMnbp7
  9mxDXDf6AU0cN/RPBjb9qSHDcWZHGzUCIG2Es59z8ugGrDY+pxLQnwfotadxd+Uy
  v/Ow5T0q5gIJAiEAyS4RaI9YG8EWx/2w0T67ZUVAw8eOMB6BIUg0Xcu+3okCIBOs
  /5OiPgoTdSy7bcF9IGpSE8ZgGKzgYQVZeN97YE00
  -----END RSA PRIVATE KEY-----
  DOC

  LOOSE = <<-DOC
  -----BEGIN FOOBAR-----
  TQIhAKMSvzIBnni7ot/OSie2TmJLY4SwTQAevXysE2RbFDYdAiEBCUEaRQnMnbp7
  TQIhAKMSvzIBnni7ot/OSie2TmJLY4SwTQAevXysE2RbFDYdAiEBCUEaRQnMnbp7
  TQIhAKMSvzIBnni7ot/OSie2TmJLY4SwTQAevXysE2RbFDYdAiEBCUEaRQnMnbp7
  -----END FOOBAR-----
  DOC

  CERTIFICATE = <<-DOC
  -----BEGIN CERTIFICATE-----
  MIIEczCCA1ugAwIBAgIBADANBgkqhkiG9w0BAQQFAD..AkGA1UEBhMCR0Ix
  EzARBgNVBAgTClNvbWUtU3RhdGUxFDASBgNVBAoTC0..0EgTHRkMTcwNQYD
  VQQLEy5DbGFzcyAxIFB1YmxpYyBQcmltYXJ5IENlcn..XRpb24gQXV0aG9y
  aXR5MRQwEgYDVQQDEwtCZXN0IENBIEx0ZDAeFw0wMD..TUwMTZaFw0wMTAy
  MDQxOTUwMTZaMIGHMQswCQYDVQQGEwJHQjETMBEGA1..29tZS1TdGF0ZTEU
  MBIGA1UEChMLQmVzdCBDQSBMdGQxNzA1BgNVBAsTLk..DEgUHVibGljIFBy
  aW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFD..AMTC0Jlc3QgQ0Eg
  THRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCg..Tz2mr7SZiAMfQyu
  vBjM9OiJjRazXBZ1BjP5CE/Wm/Rr500PRK+Lh9x5eJ../ANBE0sTK0ZsDGM
  ak2m1g7oruI3dY3VHqIxFTz0Ta1d+NAjwnLe4nOb7/..k05ShhBrJGBKKxb
  8n104o/5p8HAsZPdzbFMIyNjJzBM2o5y5A13wiLitE..fyYkQzaxCw0Awzl
  kVHiIyCuaF4wj571pSzkv6sv+4IDMbT/XpCo8L6wTa..sh+etLD6FtTjYbb
  rvZ8RQM1tlKdoMHg2qxraAV++HNBYmNWs0duEdjUbJ..XI9TtnS4o1Ckj7P
  OfljiQIDAQABo4HnMIHkMB0GA1UdDgQWBBQ8urMCRL..5AkIp9NJHJw5TCB
  tAYDVR0jBIGsMIGpgBQ8urMCRLYYMHUKU5AkIp9NJH..aSBijCBhzELMAkG
  A1UEBhMCR0IxEzARBgNVBAgTClNvbWUtU3RhdGUxFD..AoTC0Jlc3QgQ0Eg
  THRkMTcwNQYDVQQLEy5DbGFzcyAxIFB1YmxpYyBQcm..ENlcnRpZmljYXRp
  b24gQXV0aG9yaXR5MRQwEgYDVQQDEwtCZXN0IENBIE..DAMBgNVHRMEBTAD
  AQH/MA0GCSqGSIb3DQEBBAUAA4IBAQC1uYBcsSncwA..DCsQer772C2ucpX
  xQUE/C0pWWm6gDkwd5D0DSMDJRqV/weoZ4wC6B73f5..bLhGYHaXJeSD6Kr
  XcoOwLdSaGmJYslLKZB3ZIDEp0wYTGhgteb6JFiTtn..sf2xdrYfPCiIB7g
  BMAV7Gzdc4VspS6ljrAhbiiawdBiQlQmsBeFz9JkF4..b3l8BoGN+qMa56Y
  It8una2gY4l2O//on88r5IWJlm1L0oA8e4fR2yrBHX..adsGeFKkyNrwGi/
  7vQMfXdGsRrXNGRGnX+vWDZ3/zWI0joDtCkNnqEpVn..HoX
  -----END CERTIFICATE-----
  DOC

  REQUEST = <<-DOC
  -----BEGIN CERTIFICATE REQUEST-----
  MIIByjCCATMCAQAwgYkxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
  MRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKEwpHb29nbGUgSW5jMR8w
  HQYDVQQLExZJbmZvcm1hdGlvbiBUZWNobm9sb2d5MRcwFQYDVQQDEw53d3cuZ29v
  Z2xlLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEApZtYJCHJ4VpVXHfV
  IlstQTlO4qC03hjX+ZkPyvdYd1Q4+qbAeTwXmCUKYHThVRd5aXSqlPzyIBwieMZr
  WFlRQddZ1IzXAlVRDWwAo60KecqeAXnnUK+5fXoTI/UgWshre8tJ+x/TMHaQKR/J
  cIWPhqaQhsJuzZbvAdGA80BLxdMCAwEAAaAAMA0GCSqGSIb3DQEBBQUAA4GBAIhl
  4PvFq+e7ipARgI5ZM+GZx6mpCz44DTo0JkwfRDf+BtrsaC0q68eTf2XhYOsq4fkH
  Q0uA0aVog3f5iJxCa3Hp5gxbJQ6zV6kJ0TEsuaaOhEko9sdpCoPOnRBm2i/XRD2D
  6iNh8f8z0ShGsFqjDgFHyF3o+lUyj+UC6H1QW7bn
  -----END CERTIFICATE REQUEST-----
  DOC

  CRL = <<-DOC
  DOC

  _pkey_public = <<-DOC
  -----BEGIN PUBLIC KEY-----
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKj34GkxFhD90vcNLYLInFEX6Ppy1tPf
  9Cnzj4p4WGeKLs1Pt8QuKUpRKfFLfRYC9AIKjbJTWit+CqvjWYzvQwECAwEAAQ==
  -----END PUBLIC KEY-----
  DOC

  _pkey_private = <<-DOC
  -----BEGIN PRIVATE KEY-----
  MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAqPfgaTEWEP3S9w0t
  gsicURfo+nLW09/0KfOPinhYZ4ouzU+3xC4pSlEp8Ut9FgL0AgqNslNaK34Kq+NZ
  jO9DAQIDAQABAkAgkuLEHLaqkWhLgNKagSajeobLS3rPT0Agm0f7k55FXVt743hw
  Ngkp98bMNrzy9AQ1mJGbQZGrpr4c8ZAx3aRNAiEAoxK/MgGeeLui385KJ7ZOYktj
  hLBNAB69fKwTZFsUNh0CIQEJQRpFCcydunv2bENcN/oBTRw39E8GNv2pIcNxZkcb
  NQIgbYSzn3Py6AasNj6nEtCfB+i1p3F35TK/87DlPSrmAgkCIQDJLhFoj1gbwRbH
  /bDRPrtlRUDDx44wHoEhSDRdy77eiQIgE6z/k6I+ChN1LLttwX0galITxmAYrOBh
  BVl433tgTTQ=
  -----END PRIVATE KEY-----
  DOC

  EC_PARAMS = <<-DOC
  -----BEGIN EC PARAMETERS-----
  BgUrgQQACg==
  -----END EC PARAMETERS-----
  DOC

  EC_PRIVATE = <<-DOC
  -----BEGIN EC PRIVATE KEY-----
  MHQCAQEEIKYV1xoz6smkpdMksfgI8/3465V02UZdaKj4JSH30bBhoAcGBSuBBAAK
  oUQDQgAEO1O+/xRGEVJgBEAOQorBveXPTQS3c7MA+9R+HEMP7TkscI9FONPclcRb
  5sXZJjYHNYWhvxuXdGl8QrFVRIVBYg==
  -----END EC PRIVATE KEY-----
  DOC

  DSA_PUBLIC = <<-DOC
  -----BEGIN DSA PUBLIC KEY-----
  AoGAD16Uzz+jXBZqIfdtYMPNqwkUmEXphEbvjpVZwy5YskIqKB5+AI7TZQfHFroC
  S/LH6uWVYNpTukQ2fb52q8klLFFna+WlBqVJBV4QhC1clYfutjPKUpK6s8yiLyDG
  D1h4cwhZEsEB53UfHIWd2pVmy2E/emVPQoBW0/qYQLhdyMU=
  -----END DSA PUBLIC KEY-----
  DOC

  DSA_PARAMS = <<-DOC
  -----BEGIN DSA PARAMETERS-----
  MIIBHgKBgQC2grUl+ofVa7A7tB8QICqyJudylXoQ76QM+VtymvnYGtejrV6i2uQW
  Be94Za9zVkz1kz66XjY4lQdBQ3RqpT0KOnIPCiBZ2sccl1MKbVqcg0p6rnAGwyzG
  yRJP5jw3jekcgeXzzfXmvflZSPjBfhJub6NPqsfJaCPOJo5AecLPQQIVAKXZjsqx
  QPFbLWJc7ciyfS84Ag0lAoGAW6qWBeZevOHylvBQTOJ5ZZMOYiLL8dQx2AhoTn3f
  IkFL2qu6SplL43V8CJjyN42c7TeaR+ZRP+XG9fuV2iLan5L8zZ80Xg8ef2wLg61Z
  yZmEh1XVX2nI7IVhQVzimX7xd9KmOcva3GrtkA86BGMlO6J7xNHNoA4QhtGnoTAW
  qS8=
  -----END DSA PARAMETERS-----
  DOC

  DSA_PRIVATE = <<-DOC
  -----BEGIN DSA PRIVATE KEY-----
  MIIBugIBAAKBgQC2grUl+ofVa7A7tB8QICqyJudylXoQ76QM+VtymvnYGtejrV6i
  2uQWBe94Za9zVkz1kz66XjY4lQdBQ3RqpT0KOnIPCiBZ2sccl1MKbVqcg0p6rnAG
  wyzGyRJP5jw3jekcgeXzzfXmvflZSPjBfhJub6NPqsfJaCPOJo5AecLPQQIVAKXZ
  jsqxQPFbLWJc7ciyfS84Ag0lAoGAW6qWBeZevOHylvBQTOJ5ZZMOYiLL8dQx2Aho
  Tn3fIkFL2qu6SplL43V8CJjyN42c7TeaR+ZRP+XG9fuV2iLan5L8zZ80Xg8ef2wL
  g61ZyZmEh1XVX2nI7IVhQVzimX7xd9KmOcva3GrtkA86BGMlO6J7xNHNoA4QhtGn
  oTAWqS8CgYAPXpTPP6NcFmoh921gw82rCRSYRemERu+OlVnDLliyQiooHn4AjtNl
  B8cWugJL8sfq5ZVg2lO6RDZ9vnarySUsUWdr5aUGpUkFXhCELVyVh+62M8pSkrqz
  zKIvIMYPWHhzCFkSwQHndR8chZ3alWbLYT96ZU9CgFbT+phAuF3IxQIUZ8KYNKuQ
  Dx9ZfV4yGp1ff29LbLI=
  -----END DSA PRIVATE KEY-----
  DOC

  TRUSTED = <<-DOC
  -----BEGIN TRUSTED CERTIFICATE-----
  MIIEIDCCAwigAwIBAgIQNE7VVyDV7exJ9C/ON9srbTANBgkqhkiG9w0BAQUFADCB
  qTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDHRoYXd0ZSwgSW5jLjEoMCYGA1UECxMf
  Q2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjE4MDYGA1UECxMvKGMpIDIw
  MDYgdGhhd3RlLCBJbmMuIC0gRm9yIGF1dGhvcml6ZWQgdXNlIG9ubHkxHzAdBgNV
  BAMTFnRoYXd0ZSBQcmltYXJ5IFJvb3QgQ0EwHhcNMDYxMTE3MDAwMDAwWhcNMzYw
  NzE2MjM1OTU5WjCBqTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDHRoYXd0ZSwgSW5j
  LjEoMCYGA1UECxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjE4MDYG
  A1UECxMvKGMpIDIwMDYgdGhhd3RlLCBJbmMuIC0gRm9yIGF1dGhvcml6ZWQgdXNl
  IG9ubHkxHzAdBgNVBAMTFnRoYXd0ZSBQcmltYXJ5IFJvb3QgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCsoPD7gFnUnMekz52hWXMJEEUMDSxuaPFs
  W0hoSVk3/AszGcJ3f8wQLZU0HObrTQmnHNK4yZc2AreJ1CRfBsDMRJSUjQJib+ta
  3RGNKJpchJAQeg29dGYvajig4tVUROsdB58Hum/u6f1OCyn1PoSgAfGcq/gcfomk
  6KHYcWUNo1F77rzSImANuVud37r8UVsLr5iy6S7pBOhih94ryNdOwUxkHt3Ph1i6
  Sk/KaAcdHJ1KxtUvkcx8cXIcxcBn6zL9yZJclNqFwJu/U30rCfSMnZEfl2pSy94J
  NqR32HuHUETVPm4pafs5SSYeCaWAe0At6+gnhcn+Yf1+5nyXHdWdAgMBAAGjQjBA
  MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBR7W0XP
  r87Lev0xkhpqtvNG61dIUDANBgkqhkiG9w0BAQUFAAOCAQEAeRHAS7ORtvzw6WfU
  DW5FvlXok9LOAz/t2iWwHVfLHjp2oEzsUHboZHIMpKnxuIvW1oeEuzLlQRHAd9mz
  YJ3rG9XRbkREqaYB7FViHXe4XI5ISXycO1cRrK1zN44veFyQaEfZYGDm/Ac9IiAX
  xPcW6cTYcvnIc3zfFi8VqT79aie2oetaupgf1eNNZAqdE8hhuvU5HIe6uL17In/2
  /qxAeeWsEG89jxt5dovEN7MhGITlNgDrYyCZuen+MwS7QcjBAvlEYyCegc5C09Y/
  LHbTY5xZ3Y+m4Q6gLkH3LpVHz7z9M/P2C2F+fpErgUfCJzDupxBdN49cOSvkBPB7
  jVaMaDAMMAoGCCsGAQUFBwMB
  -----END TRUSTED CERTIFICATE-----
  DOC

  DH_PARAMS = <<-DOC
  -----BEGIN DH PARAMETERS-----
  MIICCAKCAgEAsb8mBiOtYJZ3XR7f/rCXQwpAAnUPXf7l9pwjYxxy30A7rIzMTrsz
  bXuhhEmzroJcDqKbu2nIzOBNO6HuyQ3n9x/ZbY5kiEt6q7UrB5jC9LwyPASZhd/F
  6xLC7yqFs9sdCaXzuyMS4Ep5sPH6lOvftdsuGZZF9HriTepv/lpD1cPtab+3vHZX
  IELVc2WBwVzvNRGd/SQB8RJ+NNF8IseCV/pb/tb67O1p7sn+JsD5xgNB7Lte/XjD
  QBXv86aNuI2Z6zAuCiQsQ4rJuWcdnyAz0+zW9DRHz0osB1+IfHYcf4tNmvMKbC8E
  u/vI+Q2WsMXkbTyhWibV2zH8cXdfsj5xpIgtbxm4G1ELGFgqyX9LD0IddXE7Md86
  qwoKSTBNOyCIEZwwNfKDXY0b7zzObv7b3//J7gM323bAcm9g3uVaYBxF7ITd/jGm
  AxpnF55mfhAOYemPZtNinnPAdvqf6BhZe29wfVC1yCIhg7ec9spRaFn2GgW0eL3d
  q/+Ux8DJBtzKE10YyLa7bh1Dhml/xtA7rpqLL4+jg5c6lLEvSGmAZtm879NYS0za
  33/2LN0/KB4z46Ro5hwqq3UIIe8oDsxdlNGb0mb9F0lKw5//J24PK/t11qMt8yuG
  oKUE7TkDfwXlEBxd/ynW2/kLIjhG1JG55Vz8GWet8+ZGzfl/VQeUb9MCAQI=
  -----END DH PARAMETERS-----
  DOC

  ECDSA_PUBLIC = <<-DOC
  -----BEGIN ECDSA PUBLIC KEY-----
  MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEgdbEVNZNiiBfApbVzlTZ6iv4KhNCiQFS
  I8eDwUdKlgbN6VhNoLdEzNdNHIXYB6H60C3CFA8MwNCNIthVsdRSfg==
  -----END ECDSA PUBLIC KEY----- 
  DOC

  ECDSA = ECDSA_PUBLIC

  EC = [EC_PARAMS, EC_PRIVATE]

  PARAMS = [DH_PARAMS, DSA_PARAMS, EC_PARAMS]

  DSA = [DSA_PARAMS, DSA_PRIVATE, DSA_PUBLIC]

  PKEY_PUBLIC = [_pkey_public, RSA_PUBLIC, DSA_PUBLIC, ECDSA_PUBLIC]

  PKEY_PRIVATE = [_pkey_private, RSA_PRIVATE, DSA_PRIVATE, EC_PRIVATE]

  PKEY = [PKEY_PUBLIC, PKEY_PRIVATE].flatten

  RSA = [RSA_PUBLIC, RSA_PRIVATE]
end
