# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
#  chop.rb
#
# ---- original file header ----
#
# @summary
#       @summary
#      **Deprecated** Returns a new string with the last character removed.
#
#    If the string ends with `
#`, both characters are removed. Applying
#    chop to an empty string returns an empty string. If you wish to merely
#    remove record separators then you should use the `chomp` function.
#    Requires a string or array of strings as input.
#
#    > *Note:* **Deprecated** from Puppet 6.0.0, this function has been replaced with a
#    built-in [`chop`](https://puppet.com/docs/puppet/latest/function.html#chop) function.
#
#    @return [String] The given String, sans the last character.
#
#
Puppet::Functions.create_function(:'stdlib::chop') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    raise(Puppet::ParseError, "chop(): Wrong number of arguments given (#{arguments.size} for 1)") if arguments.empty?

    value = arguments[0]

    unless value.is_a?(Array) || value.is_a?(String)
      raise(Puppet::ParseError, 'chop(): Requires either an array or string to work with')
    end

    result = if value.is_a?(Array)
               # Numbers in Puppet are often string-encoded which is troublesome ...
               value.map { |i| i.is_a?(String) ? i.chop : i }
             else
               value.chop
             end

    return result
  
  end
end
