# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# get_module_path.rb
#
# ---- original file header ----
#
# @summary
#       @summary
#      Returns the absolute path of the specified module for the current
#      environment.
#
#    @return
#      Returns the absolute path of the specified module for the current
#      environment.
#
#    @example Example Usage:
#      $module_path = get_module_path('stdlib')
#
#    > *Note:*
#      that since Puppet 5.4.0 the  built-in
#      [`module_directory`](https://puppet.com/docs/puppet/latest/function.html#module_directory)
#      function in Puppet does the same thing and will return the path to the first found module
#      if given multiple values or an array.
#
#
Puppet::Functions.create_function(:'stdlib::get_module_path') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end

  def default_impl(*args)
    raise(Puppet::ParseError, 'get_module_path(): Wrong number of arguments, expects one') unless args.size == 1
    module_path = Puppet::Module.find(args[0], compiler.environment.to_s)
    raise(Puppet::ParseError, "Could not find module #{args[0]} in environment #{compiler.environment}") unless module_path
    module_path.path
  end
end
