# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# grep.rb
#
# ---- original file header ----
#
# @summary
#       @summary
#      This function searches through an array and returns any elements that match
#      the provided regular expression.
#
#    @return
#      array of elements that match the provided regular expression.
#    @example Example Usage:
#      grep(['aaa','bbb','ccc','aaaddd'], 'aaa') # Returns ['aaa','aaaddd']
#
#    > **Note:** that since Puppet 4.0.0, the built-in
#    [`filter`](https://puppet.com/docs/puppet/latest/function.html#filter) function does
#    the "same" - as any logic can be used to filter, as opposed to just regular expressions:
#    ```['aaa', 'bbb', 'ccc', 'aaaddd']. filter |$x| { $x =~ 'aaa' }```
#
#
Puppet::Functions.create_function(:'stdlib::grep') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    if arguments.size != 2
      raise(Puppet::ParseError, "grep(): Wrong number of arguments given #{arguments.size} for 2")
    end

    a = arguments[0]
    pattern = Regexp.new(arguments[1])

    a.grep(pattern)
  
  end
end
