# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# parseyaml.rb
#
# ---- original file header ----
#
# @summary
#       @summary
#      This function accepts YAML as a string and converts it into the correct
#      Puppet structure.
#
#    @return
#      converted YAML into Puppet structure
#
#    > *Note:*
#      The optional second argument can be used to pass a default value that will
#      be returned if the parsing of YAML string have failed.
#
#
Puppet::Functions.create_function(:'stdlib::parseyaml') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    
    raise ArgumentError, 'Wrong number of arguments. 1 or 2 arguments should be provided.' unless arguments.length >= 1
    require 'yaml'

    begin
      YAML.load(arguments[0]) || arguments[1] # rubocop:disable Security/YAMLLoad : using YAML.safe_load causes the code to break
      # in ruby 1.9.3 Psych::SyntaxError is a RuntimeException
      # this still needs to catch that and work also on rubies that
      # do not have Psych available.
    rescue StandardError, Psych::SyntaxError => e # rubocop:disable Lint/ShadowedException : See above
      raise e unless arguments[1]
      arguments[1]
    end
  
  end
end
