# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# values.rb
#
# ---- original file header ----
#
# @summary
#       @summary
#      When given a hash this function will return the values of that hash.
#
#    @return
#      array of values
#
#    @example **Usage**
#      $hash = {
#        'a' => 1,
#        'b' => 2,
#        'c' => 3,
#      }
#      values($hash)
#
#      This example would return: ```[1,2,3]```
#
#    > *Note:*
#    From Puppet 5.5.0, the compatible function with the same name in Puppet core
#    will be used instead of this function.
#
#
#
Puppet::Functions.create_function(:'stdlib::values') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    raise(Puppet::ParseError, "values(): Wrong number of arguments given (#{arguments.size} for 1)") if arguments.empty?

    hash = arguments[0]

    unless hash.is_a?(Hash)
      raise(Puppet::ParseError, 'values(): Requires hash to work with')
    end

    result = hash.values

    return result
  
  end
end
